name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Repo
        run: |
          git remote add upstream https://github.com/FlightControl-Master/MOOSE.git
          git fetch upstream

      # - name: Sync with Upstream
      #   run: |
      #     git merge upstream/main --allow-unrelated-histories || true # Replace `main` with the upstream branch name
      #     git push origin main

      - name: Sync Branches
        run: |
          # List the branches to sync
          branches=("main")
          
          for branch in "${branches[@]}"; do
            echo "Syncing branch: $branch"
            git checkout $branch || git checkout -b $branch
            git merge upstream/$branch --allow-unrelated-histories || true
            git push origin $branch
          done

